log_save_path: ./log_save/test.txt



device: cuda:0

client_num: 2
dataset: cifar10
dataset_repo: ./dataRepo/cifar10
batch: 256
epochs: 100
poison_rate: 0.3
abl_epochs: 20
isolation_ratio: 0.01

gamma: 0.5

strategy: [16,16]
trigger_size: 3

poisoning_epoch: 100
begin_embeding_swap: 
  cifar10: 60
  mnist: 14
  imagenette: 10
  cinic10: 8
  BM: 6
  GM: 40

opt: Adam

SGD:
  lr: 0.2
  weight_decay: 0.0005
  momentum: 0.9

Adam:
  lr: 0.001
  weight_decay: 0.0001
