log_save_path: ./log_save/test.txt

device: cuda:0

client_num: 2
dataset: cifar10
dataset_repo: ./dataRepo/cifar10
batch: 256
half: 16
epochs: 100

Score_type: div
iso_k: 3
add_noise: False
top: 1  # Top-k Accuracy
split_strategy: [16, 16]
gamma: 0.5
abl_epochs: 20
begin_embeding_swap: 
  cifar10: 80
  cifar100: 20
  mnist: 14
  imagenette: 10
  cinic10: 8
  BM: 6
  GM: 40
opt: Adam
isolation_ratio: 0.01
SGD:
  lr: 0.2
  weight_decay: 0.0005
  momentum: 0.9

Adam:
  lr: 0.001
  weight_decay: 0.0001

